project: pr2_reaching
sampling_hz: 18.0

topic: 
    AngleVector:
        name: /joint_states
        rosbag: True
        auxiliary: False
        use: True
    RGBImage: 
        name: /kinect_head/rgb/image_rect_color
        rosbag: True
        auxiliary: True
        use: True
    DepthImage: 
        name: /kinect_head/depth_registered/image
        rosbag: True
        auxiliary: False
        use: False
    GripperState:
        name: /r_gripper_controller/state
        rosbag: True
        auxiliary: True
        use: True

control_joints:
    - r_shoulder_pan_joint 
    - r_shoulder_lift_joint
    - r_upper_arm_roll_joint
    - r_elbow_flex_joint
    - r_forearm_roll_joint
    - r_wrist_flex_joint 
    - r_wrist_roll_joint
