#!/bin/bash

function train_autoencoder {
    local project_name=$1
    local epoch=$2
    local image_type=RGBImage
    python3 -m mohou.script.train_autoencoder -pn $project_name -n $epoch -image $image_type -latent 16 --vae -chunk_postfix autoencoder
    python3 -m mohou.script.visualize_autoencoder_result -pn $project_name
    python3 -m mohou.script.visualize_train_history -pn $project_name
}

function train_lstm {
    local project_name=$1
    local epoch=$2
    python3 -m mohou.script.train_lstm -pn $project_name -n $epoch -aug 19
    python3 -m mohou.script.visualize_lstm_result -pn $project_name
    python3 -m mohou.script.visualize_train_history -pn $project_name
}

project_name=$1
n_epoch_ae=$2
n_epoch_lstm=$3

train_autoencoder $project_name $n_epoch_ae
train_lstm $project_name $n_epoch_lstm
