#!/bin/bash

project_name=$1

function train_autoencoder {
    local project_name=$1
    local image_type=$2Image
    python3 -m mohou.script.train_autoencoder -pn $project_name -n 2000 -image $image_type -latent 16 --vae -chunk_postfix image_autoencoder
    python3 -m mohou.script.visualize_autoencoder_result -pn $project_name
    python3 -m mohou.script.visualize_train_history -pn $project_name
}

function train_lstm {
    local project_name=$1
    python3 -m mohou.script.train_lstm -pn $project_name -n 20000 -aug 19
    python3 -m mohou.script.visualize_lstm_result -pn $project_name
    python3 -m mohou.script.visualize_train_history -pn $project_name
}

train_autoencoder $project_name RGB
train_lstm $project_name
