name: lint

on:
    push:
        branches:
            - master
            - devel
    pull_request:
        branches:
            - master
            - devel

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Code
          uses: actions/checkout@v2
        - name: pip install formatters
          run: |
              pip3 install black==22.6.0
              pip3 install isort
              pip3 install flake8
              cd /tmp && git clone https://github.com/knorth55/euslint.git && cd euslint && pip3 install -e .

        - name: check by euslint
          run: |
              find . -name "*.l" | xargs -i euslint {}

        - name: check by black
          run: |
              black --version
              black --check .
        - name: check by isort
          run: |
              isort --version-number
              isort --check-only --quiet . 
        - name: check by flake8
          run: |
              flake8 --version
              flake8 .
