name: rostest-melodic

on:
    push:
        branches:
            - master
            - devel
    pull_request:
        branches:
            - master
            - devel
    schedule:
        - cron: '30 1,13 * * *'

jobs:
  test:
    runs-on: ubuntu-18.04
    env:
      CATKIN_WS: /home/runner/work/catkin_ws
    steps:
    - uses: actions/checkout@v2

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: melodic

    - name: Init workspace
      run: |
        sudo apt-get install python3-catkin-pkg-modules python3-rospkg-modules python3-venv python3-empy
        sudo apt-get install python-catkin-tools python-wstool ros-melodic-rostest
        source /opt/ros/melodic/setup.bash
        mkdir -p ${CATKIN_WS}/src
        ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/

    - name: install package
      run: |
        source /opt/ros/melodic/setup.bash
        cd ${CATKIN_WS}/src && wstool init
        wstool set -y geometry2 --git https://github.com/ros/geometry2 -v 0.6.5
        wstool update
        rosdep update
        rosdep install --from-paths . -i -r -y
        cd ${CATKIN_WS} && catkin init
        catkin config -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so
        catkin build
        source ${CATKIN_WS}/devel/setup.bash
        pip3 install scikit-build
        roscd mohou_ros && pip3 install . --user

    - name: temp install skrobot
      run: |
          git clone https://github.com/HiroIshida/scikit-robot.git --branch raise_import_error && cd scikit-robot && pip3 install . && cd .. && rm -rf scikit-robot

    - name: Show installed package
      run: |
          dpkg -l
          pip3 freeze

    - name: rostest data_collection
      run: |
        source ${CATKIN_WS}/devel/setup.bash
        rostest mohou_ros data_collection.test

    - name: rostest train_pipeline
      run: |
        source ${CATKIN_WS}/devel/setup.bash
        rostest mohou_ros train_pipeline.test

    - name: rostest executor
      run: |
        source ${CATKIN_WS}/devel/setup.bash
        rostest mohou_ros executor.test
