name: rostest-noetic

on:
    push:
        branches:
            - master
            - devel
    pull_request:
        branches:
            - master
            - devel
    schedule:
        - cron: '30 1,13 * * *'

jobs:
  test:
    runs-on: ubuntu-20.04
    env:
      CATKIN_WS: /home/runner/work/catkin_ws
    steps:
    - uses: actions/checkout@v2

    - name: Setup ROS
      uses: ros-tooling/setup-ros@v0.2
      with:
        required-ros-distributions: noetic

    - name: Init workspace
      run: |
        sudo apt-get install python3-osrf-pycommon python3-catkin-tools
        source /opt/ros/noetic/setup.bash
        mkdir -p ${CATKIN_WS}/src
        ln -s ${GITHUB_WORKSPACE} ${CATKIN_WS}/src/

    - name: install package
      run: |
        source /opt/ros/noetic/setup.bash
        cd ${CATKIN_WS}/src && rosdep update
        rosdep install --from-paths . -i -r -y
        cd ${CATKIN_WS} && catkin init
        catkin build
        pip3 install scikit-build
        roscd mohou_ros && pip3 install . --user

    - name: Show installed package
      run: |
          dpkg -l
          pip3 freeze

    - name: rostest data_collection
      run: |
        source ${CATKIN_WS}/devel/setup.bash
        rostest mohou_ros data_collection.test

    - name: rostest train_pipeline
      run: |
        source ${CATKIN_WS}/devel/setup.bash
        rostest mohou_ros train_pipeline.test

    - name: rostest executor
      run: |
        source ${CATKIN_WS}/devel/setup.bash
        rostest mohou_ros executor.test
