name: integration test

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            ros-env:
              - ROS_DISTRO: melodic
                BUILDER: catkin_tools_devel

        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
            - name: Setup ROS
              uses: 'ros-industrial/industrial_ci@master'
              env: ${{matrix.ros-env}}
