name: RosTest

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            ros-env:
              - ROS_DISTRO: noetic
                BUILDER: catkin_tools_devel
                WRITABLE_SOUCE: true
                BEFORE_RUN_TARGET_TEST:
                    pip3 install . --user
                ADDITIONAL_DEBS: |
                    wget git
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2
              with:
                submodules: recursive # Checkout yamaopt as git submodule

            - name: Setup ROS
              uses: 'ros-industrial/industrial_ci@master'
              env: ${{matrix.ros-env}}
