name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Code
              uses: actions/checkout@v2

            - name: Setup python
              uses: actions/setup-python@v2
              with:
                  python-version: '3.7'

            - name: pip install this package
              run: |
                  pip3 install -e .
                  # All these packages are included in ros, but I just want to run CI quickly
                  pip install --extra-index-url https://rospypi.github.io/simple/ rospy
                  pip install --extra-index-url https://rospypi.github.io/simple/ rosbag
                  pip install --extra-index-url https://rospypi.github.io/simple/ cv_bridge
                  pip install --extra-index-url https://rospypi.github.io/simple/ opencv-python
                  pip install --extra-index-url https://rospypi.github.io/simple/ std_msgs
                  pip install --extra-index-url https://rospypi.github.io/simple/ geometry_msgs
                  pip install --extra-index-url https://rospypi.github.io/simple/ sensor_msgs

            - name: pip install pytest mypy
              run: |
                  pip3 install pytest
                  pip3 install mypy==0.910

            - name: pip install formatting
              run: |
                python -m pip install --upgrade pip
                pip install hacking isort

            - name: Check format
              run: flake8 .

            - name: Run Pytest
              run: |
                  pytest -v tests

            - name: Run mypy
              run: mypy . --exclude setup.py
